# Generated by Django 3.2.5 on 2021-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('kr', 'Korean')], default='kr', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('books', 'Books'), ('movies', 'Movies')], default='books', max_length=6),
        ),
    ]
