# Generated by Django 3.2.5 on 2021-07-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('year', models.DateField()),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('rating', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person_writer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
