# Generated by Django 3.2.5 on 2021-08-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('categories', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(limit_choices_to={'kind': 'actor'}, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(limit_choices_to={'kind': 'movie'}, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(limit_choices_to={'kind': 'director'}, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='people.person'),
        ),
    ]
